package com.mg.api.model;

import java.util.Date;

public class Album {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.title
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.introduce
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.cover
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.tag
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.view_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Integer viewCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.like_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Integer likeCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.reply_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Integer replyCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.update_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.id
     *
     * @return the value of album.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.id
     *
     * @param id the value for album.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.uid
     *
     * @return the value of album.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.uid
     *
     * @param uid the value for album.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.title
     *
     * @return the value of album.title
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.title
     *
     * @param title the value for album.title
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.introduce
     *
     * @return the value of album.introduce
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.introduce
     *
     * @param introduce the value for album.introduce
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.cover
     *
     * @return the value of album.cover
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.cover
     *
     * @param cover the value for album.cover
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.tag
     *
     * @return the value of album.tag
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.tag
     *
     * @param tag the value for album.tag
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.view_cnt
     *
     * @return the value of album.view_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Integer getViewCnt() {
        return viewCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.view_cnt
     *
     * @param viewCnt the value for album.view_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setViewCnt(Integer viewCnt) {
        this.viewCnt = viewCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.like_cnt
     *
     * @return the value of album.like_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Integer getLikeCnt() {
        return likeCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.like_cnt
     *
     * @param likeCnt the value for album.like_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setLikeCnt(Integer likeCnt) {
        this.likeCnt = likeCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.reply_cnt
     *
     * @return the value of album.reply_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Integer getReplyCnt() {
        return replyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.reply_cnt
     *
     * @param replyCnt the value for album.reply_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setReplyCnt(Integer replyCnt) {
        this.replyCnt = replyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.create_date
     *
     * @return the value of album.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.create_date
     *
     * @param createDate the value for album.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.update_date
     *
     * @return the value of album.update_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.update_date
     *
     * @param updateDate the value for album.update_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}