package com.mg.api.model;

import java.util.Date;

public class LikeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.type
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.pid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.id
     *
     * @return the value of like_record.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.id
     *
     * @param id the value for like_record.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.uid
     *
     * @return the value of like_record.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.uid
     *
     * @param uid the value for like_record.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.type
     *
     * @return the value of like_record.type
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.type
     *
     * @param type the value for like_record.type
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.pid
     *
     * @return the value of like_record.pid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.pid
     *
     * @param pid the value for like_record.pid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.create_date
     *
     * @return the value of like_record.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.create_date
     *
     * @param createDate the value for like_record.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}