package com.mg.api.model;

public class Location {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.id
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.pid
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.name
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.short_name
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    private String shortName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.id
     *
     * @return the value of location.id
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.id
     *
     * @param id the value for location.id
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.pid
     *
     * @return the value of location.pid
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.pid
     *
     * @param pid the value for location.pid
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.name
     *
     * @return the value of location.name
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.name
     *
     * @param name the value for location.name
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.short_name
     *
     * @return the value of location.short_name
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.short_name
     *
     * @param shortName the value for location.short_name
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }
}