package com.mg.api.model;

import java.util.Date;

public class Multimedia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.title
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.introduce
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.cover
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.rid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.type
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.tag
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.view_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Integer viewCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.like_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Integer likeCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.reply_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Integer replyCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multimedia.update_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.id
     *
     * @return the value of multimedia.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.id
     *
     * @param id the value for multimedia.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.uid
     *
     * @return the value of multimedia.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.uid
     *
     * @param uid the value for multimedia.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.title
     *
     * @return the value of multimedia.title
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.title
     *
     * @param title the value for multimedia.title
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.introduce
     *
     * @return the value of multimedia.introduce
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.introduce
     *
     * @param introduce the value for multimedia.introduce
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.cover
     *
     * @return the value of multimedia.cover
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.cover
     *
     * @param cover the value for multimedia.cover
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.rid
     *
     * @return the value of multimedia.rid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.rid
     *
     * @param rid the value for multimedia.rid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setRid(String rid) {
        this.rid = rid == null ? null : rid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.type
     *
     * @return the value of multimedia.type
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.type
     *
     * @param type the value for multimedia.type
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.tag
     *
     * @return the value of multimedia.tag
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.tag
     *
     * @param tag the value for multimedia.tag
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.view_cnt
     *
     * @return the value of multimedia.view_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Integer getViewCnt() {
        return viewCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.view_cnt
     *
     * @param viewCnt the value for multimedia.view_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setViewCnt(Integer viewCnt) {
        this.viewCnt = viewCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.like_cnt
     *
     * @return the value of multimedia.like_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Integer getLikeCnt() {
        return likeCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.like_cnt
     *
     * @param likeCnt the value for multimedia.like_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setLikeCnt(Integer likeCnt) {
        this.likeCnt = likeCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.reply_cnt
     *
     * @return the value of multimedia.reply_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Integer getReplyCnt() {
        return replyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.reply_cnt
     *
     * @param replyCnt the value for multimedia.reply_cnt
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setReplyCnt(Integer replyCnt) {
        this.replyCnt = replyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.create_date
     *
     * @return the value of multimedia.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.create_date
     *
     * @param createDate the value for multimedia.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multimedia.update_date
     *
     * @return the value of multimedia.update_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multimedia.update_date
     *
     * @param updateDate the value for multimedia.update_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}