package com.mg.api.model;

import java.util.Date;

public class Reply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.type
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.pid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.content
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.id
     *
     * @return the value of reply.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.id
     *
     * @param id the value for reply.id
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.uid
     *
     * @return the value of reply.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.uid
     *
     * @param uid the value for reply.uid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.type
     *
     * @return the value of reply.type
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.type
     *
     * @param type the value for reply.type
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.pid
     *
     * @return the value of reply.pid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.pid
     *
     * @param pid the value for reply.pid
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.content
     *
     * @return the value of reply.content
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.content
     *
     * @param content the value for reply.content
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.create_date
     *
     * @return the value of reply.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.create_date
     *
     * @param createDate the value for reply.create_date
     *
     * @mbggenerated Fri Dec 23 11:53:28 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}