package com.mg.api.model;

import java.math.BigDecimal;
import java.util.Date;

public class UserAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.uid
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.type
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.balance
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.create_date
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.update_date
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.uid
     *
     * @return the value of user_account.uid
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.uid
     *
     * @param uid the value for user_account.uid
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.type
     *
     * @return the value of user_account.type
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.type
     *
     * @param type the value for user_account.type
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.balance
     *
     * @return the value of user_account.balance
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.balance
     *
     * @param balance the value for user_account.balance
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.create_date
     *
     * @return the value of user_account.create_date
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.create_date
     *
     * @param createDate the value for user_account.create_date
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.update_date
     *
     * @return the value of user_account.update_date
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.update_date
     *
     * @param updateDate the value for user_account.update_date
     *
     * @mbggenerated Fri Dec 30 17:34:55 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}